site_name: Ultrabroken Docs
site_description: Comprehensive documentation of the Ultrabroken glitch in The Legend of Zelda - Tears of the Kingdom
site_author: NaN Gogh & Community
copyright: Community-Driven Research
site_url: https://nan-gogh.github.io/ultrabroken-documentation/
use_directory_urls: true

theme:
  name: material
  logo: assets/images/ultrabroken_rune.svg
  favicon: assets/images/ultrabroken_rune.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - search.highlight
    - search.share
  palette:
    scheme: slate
    primary: teal
    accent: teal

extra_css:
  - assets/stylesheets/glow.css

extra_javascript:
  - assets/scripts/clipboard-permalink.js
  - assets/scripts/404-detect.js
  - assets/scripts/search-highlights-cleanup.js
  - assets/scripts/search-enter-disable.js
  

nav:
  - Home: index.md
     #- Welcome: index.md
     #- Ultrabroken: ultrabroken/index.md
     #- Entanglement: entanglement/index.md
     #- Zuggling: zuggling/index.md
     #- Glitchcraft: glitchcraft/index.md
  - Ultrabroken: 
     - Introduction: ultrabroken/index.md
     - Basics: 
        - Overview: ultrabroken/basics/index.md
        - Introduction: ultrabroken/basics/introduction.md
        - Requirements: ultrabroken/basics/requirements.md
        - Procedure: ultrabroken/basics/procedure.md
        - Exceptions: ultrabroken/basics/exceptions.md
        - Attributes: ultrabroken/basics/attributes.md
        - Theories: ultrabroken/basics/theories.md
        - Datamine: ultrabroken/basics/datamine.md
     - Effects:
        - Overview: ultrabroken/effects/index.md
        - Wacko Boingo (Flight): ultrabroken/effects/wacko-boingo.md
        - Lift Lock: ultrabroken/effects/lift-lock.md
        - Recall Fling: ultrabroken/effects/recall-fling.md
        - Ghost Glue: ultrabroken/effects/ghost-glue.md
        - Remnant Glue: ultrabroken/effects/remnant-glue.md
        - Glue Lock: ultrabroken/effects/glue-lock.md
        - Mass Matching: ultrabroken/effects/mass-matching.md
        - Ghost Smuggle: ultrabroken/effects/ghost-smuggle.md
        - Phantom Smuggle: ultrabroken/effects/phantom-smuggle.md
        - Resurrect Smuggle: ultrabroken/effects/resurrect-smuggle.md
        - Ouija Entanglement: ultrabroken/effects/ouija-entanglement.md
        - Antimass: ultrabroken/effects/antimass.md
        - Freecall: ultrabroken/effects/freecall.md
        - Quantum State Freeze: ultrabroken/effects/quantum-state-freeze.md
        - Fuse Stacking: ultrabroken/effects/fuse-stacking.md
        - Transmigration: ultrabroken/effects/transmigration.md
        - Autobuild Standalones: ultrabroken/effects/autobuild-standalones.md
        - Slidy Cart: ultrabroken/effects/slidy-cart.md
     - Devices: ultrabroken/devices/index.md
     - Builds: ultrabroken/builds/index.md
     - Tips: ultrabroken/meta.md
     - Credits: ultrabroken/credits.md
  - Entanglement:
    - Introduction: entanglement/index.md
    - Fuse Entanglement: glitchcraft/0051-fuse-entanglement.md
    - Fuse Entanglement Desync: glitchcraft/0056-fuse-entanglement-desync-fed.md
    #- Fuse Entanglement Clipping: glitchcraft/0108-fuse-entanglement-clipping-fec.md
    - Fuse Storage Fuse Entanglement: glitchcraft/0114-fuse-storage-fuse-entanglement-fsfe.md
    - Cull Fuse Entanglement: glitchcraft/0180-cull-fuse-entanglement-cull-fe.md
    - Mineru Fuse Entanglement: glitchcraft/0187-mineru-fuse-entanglement-mineru-fe.md
    - Resync Fuse Entanglement: glitchcraft/0202-resync-fuse-entanglement-resync-fe.md
    - Double Shield Desync Clip Fuse Entanglement: glitchcraft/0240-double-shield-desync-clip-fuse-entanglement-double-sdc-fe.md
    - Construct Fuse Entanglement: glitchcraft/0242-construct-fuse-entanglement.md
    - Overload Fuse Entanglement: glitchcraft/0247-overload-fuse-entanglement.md
    - Replacement Actor Fuse Entanglement: glitchcraft/0259-replacement-actor-fuse-entanglement.md
    - Fuse Overload Fuse Entanglement: glitchcraft/0277-fuse-overload-fuse-entanglement-fofe.md
    - Detanglement: glitchcraft/0172-detanglement.md
  - Zuggling: zuggling/index.md
  - Glitchcraft: glitchcraft/index.md
  - Zuggle & Smuggle Index: glitchcraft/zuggle-smuggle-index.md

plugins:
  - search
  - minify

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist
  - toc:
      permalink: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nan-gogh/ultrabroken-documentation
    - icon: fontawesome/brands/twitter
      link: https://x.com/_nan_gogh
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xM8NnTetb2
    - icon: fontawesome/brands/discord
      link: https://discord.gg/uZqvjnwqF3

watch:
  - docs
